env:
  global:
    - secure: rYsnfV9yVY8nKrxV+zgZ/YfYhi0KBhIZX89rNA7dqnNs40wXynGs+um7sPEgFnemDyKMt/fRlrPBci7Mx4StIxZnuDm8iK3v+wIOlJ0D277AWSISTOZ9DgMlySBYwbA2I2s+f1cSf8USxXCtLxI8VRLd6OnKMc2UokY9ammpldZzqjZDXbVInguM75b2qDfZUgF/TdWNKYySe3VR/xpR6SC5e6bP6vAdg7PdLob+ytfke7z9aVVVW0f8RjpJmLdBSSym2ok1bc05AdApBTozSrxMynfBTL1qcnXn6YM3fG3OgsE2lgnCHGbfeV8CJmNMrL6F3BCBwPYXKv8XltlyyoM/u39hM6P7teHRoJEHspUhfQzkXS0Y5pOxjzxu2n2rRKUs3koWWFUOHZP4yhdR8445VIChT2/LaHjielGax6CeBCQtSAcJ0vlFzU/052DEv8X8bpOy12tv2AsJsv/xZ00muhC7ttxbxZW91cWw/GJpGq1uNmJiBJ2tHRtGvGtbdiGIG0omH+imKROwEh30rFxnFpDgFburJEgMJLIe2GVcbI8N99Elwhr7fGOHW30nnKWyNgfeF5JWcA4jub847dA2rN8EOxey78s8SF9RIEXP6xyxn3sUqHGl1/5GP7Lhb1uo+xJdcSYR7uS5gNWkPSHxZlqJM9vXKElgX2uKFVw=
    - GIT_NAME: Travis CI
    - GIT_EMAIL: dead-hosts@funilrys.com
    - TRAVIS_REPO_SLUG: Ultimate-Hosts-Blacklist/Top-Attacking-IP-Addresses-Against-Wordpress-Sites
    - GIT_BRANCH: master

dist: xenial
sudo: required
language: python

python:
  - "3.7"

matrix:
  fast_finish: true

cache:
  - pip

addons:
  apt:
    packages:
      - dos2unix

install:
  - pip3 install --upgrade pip
  - pip3 install requests

script:
  - python3 ./update.py

notifications:
  on_success:   change
  on_failure:   always
