env:
  global:
    - secure: dBvENSwY5HjaVilNMWiBY1mjPA4LCBRmiq5XeD070QjgzP5AxSiYGAztPjB//Q8ceN8JGo4MwmOAK98zGFiBtzqHKSQwk+MoeneDgRcySyEG2vGLzB8p5ZuQLhWkfaNeQl6aTlqYSkxIXGhZ2Zou1hp+V8MfXzk1olSU5I1DPT2yuSALWfdH7ek5hJpkIIUYHn9RjnY75DUD8gU1J1Ao3BU+Se7oC6bZlb7eKjkjvHlUgB3YR/IRaTNBcNE+jmMQVV9mlpDmmCox3+yX9FKA3EcoKcR48CId1UsJckAgDlhj2VdXvfpXx3GrSavuc5xSsTJpD/gTkWGO02ZawC8SYlXTyUnEsDVU4AKpRkc8PjB4pa79+UIg+1+d6bFqjI30TmX1mx8HQKqBMvoiUt+anvvAjrjWi/gmyWDjr9tozoKmMyhCqPmiBkD0na3JmcCQh2ODtHKQywr5RMZvANl6g3P1dIEdIq0GFGvE9dWIpXN+1Z3YNZ8hLLtqH8r/HpgapyvqRXu2F2LAQRCPaVUYDA3ixgAZyB1Hiu1fdBQAGfzRb+E4BqhDGMkSYiixwamOWeN9yFBMsB+L4bBI/vVwWQ25QM0LNmuNg6o8HzCFkbnL+/+hjCNaEraza5uytrj52YNlGvYcmRwdpLv/V5WcIrmO8dCkLZzkngEObwvaONY=
    - GIT_NAME: Travis CI
    - GIT_EMAIL: dead-hosts@funilrys.com
    - TRAVIS_REPO_SLUG: Ultimate-Hosts-Blacklist/Top-Attacking-IP-Addresses-Against-Wordpress-Sites
    - GIT_BRANCH: master

language: python

python:
  - "3.6"

matrix:
  fast_finish: true

cache:
  - apt
  - pip

sudo: required

before_install:
  - pip3 install colorama
  - sudo apt-get -y install dos2unix

script:
  - pip3 install git+https://github.com/funilrys/PyFunceble.git@dev#egg=PyFunceble && python3 ./update.py

notifications:
  on_success:   change
  on_failure:   always
