env:
  global:
    - secure: aoEyVcl8u1wF77ecTEtTFxU6OzCBHUEupr/KnTDLdmSQX8FIL+l1sC1YS4JkmdM0DrFC2lAkSV04v8iYc2mboM9aHFGDT1uVHRLBt6JLLg/E1pMuyrF+C0SgOeoP9gB9RYWzCgsZhhT5BpW4WlEOd+xheuny6yZxgsRVty1+ICMZUHPzJrfW6ZqAkaCAc7B+Tuc0ndqE29UUxkKgrZB/Lt/7+zylPpjeo5QLACauk7qOt6EP0Z+nLr91DraKQcxKeRQYTTCyfwzdhGSZp5FUOYrVftO/IyQ7h8p+1s0+T4Q/dLH2GZpgcu3CKSbMjaGJCKreM6FglZ+i6WJZs6U/0CKqASSmaPQKqfNEz0vUvPbtqYNcxhLDQ0XnIkScOLXvJsy6NIU9fhna5lHfI6qMIHJ9pV6wUQZhSmnQdzRWy7iRyDIKx8zErCqs04nljQ8pIYKKAu/uYa+BbbffoZk0XdT2bWhJaCHztHKs2I0P63ijl/uZjLSMQd6N/IRtdkgp/fhVm1Cq2mslIW+mN0F5z1ANCMKRAaZ2LlG0SZUy8uc+mrOvFEZwtGMYpsOpUjVYH66GH3+EyRlxJDeGsK9zaIFB2qRAtll/P7o1yx4rXADppw+s8albYVumeV9Tspybz5VzT9AsGfJgr4F+kK0Vk04UjioWYY06oSvkUKnHyYA=
    - GIT_NAME: Travis CI
    - GIT_EMAIL: dead-hosts@funilrys.com
    - TRAVIS_REPO_SLUG: Ultimate-Hosts-Blacklist/Top-Attacking-IP-Addresses-Against-Wordpress-Sites
    - GIT_BRANCH: master

language: python

python:
  - "3.6"

matrix:
  fast_finish: true

cache:
  - apt
  - pip

sudo: required

before_install:
  - pip3 install colorama
  - sudo apt-get -y install dos2unix

script:
  - pip3 install git+https://github.com/funilrys/PyFunceble.git@dev#egg=PyFunceble && python3 ./update.py

notifications:
  on_success:   change
  on_failure:   always
