env:
  global:
    - secure: kshFZCKcIdeCyuT1ihKSBwSM7LNNY6nBqk5AQUhgoOlVAZ0Fgup6223i6w9xBaOtZBzVIoQa4qgPGa39lc9mzcohPPNx6WixJk+Rd0ime/Zw3qChDzOUulCiiVKu+d+Biz0JHfszL1uDnuhN+bpMArXAAppzD6ME8bZ1VQegQy3kFh6zgUU1BukQNYHKKaozxIkNpGwcFVPZC0u8mFKvkeJQtdg328gm4+5X461RhGKX4ocpnCUWuFjnPjNdLEvMmV1TMXLYezf51pu9fq4c6hRexTYH9AiZlt2ED1afCd1oq1z8JOU0o2SWvQyeRFDam2lbm9em8k/h5zstaLi8G4v1bQ2is9ICkvyA+2v9BQvDbvCX+K+nkD7zjOP/pYJt2SkgHmsMZ0Q0ZtDwdpDkNiEeAGPzl5UD6PZ32c2D+tZqENKqjq5XOTyxizAGPUNcyI68Sqd34qZHg8MeblSPqbtvaZE4RlUwUHwCAG4wBSVWqMqCm7KR1k3MwyC/btKOkrgKb8Wu3AWevwG+Cetna/+a4PQzDOH9F+YXemMGf348Z8uIjmKrwXzrG0mjQzb5MCrXsh2RH7L28tj7kRjjAqjtB/SH0XDgQzl6abcIrf/uvMQLWfk5NIQcNwxRZIlYRhCdAGqkDYo55N8hyJo4Xrg7gICdPZnCVLPT9deZNds=
    - GIT_NAME: Travis CI
    - GIT_EMAIL: dead-hosts@funilrys.com
    - TRAVIS_REPO_SLUG: Ultimate-Hosts-Blacklist/Top-Attacking-IP-Addresses-Against-Wordpress-Sites
    - GIT_BRANCH: master

dist: xenial
sudo: required
language: python

python:
  - "3.7"

matrix:
  fast_finish: true

cache:
  - pip

addons:
  apt:
    packages:
      - dos2unix

install:
  - pip3 install --upgrade pip
  - pip3 install requests

script:
  - python3 ./update.py

notifications:
  on_success:   change
  on_failure:   always
