env:
  global:
    - secure: bLt77hMalZruvEd9jJe/Z0P+u7ljktXLG3zPUieTo2EZsXk9IZL/a4Fs7gwPWAM5YW7M2wKIaAnco3vt3PAsqj0+E+SQViLBxbmVsiPgGqp/a2QqWMW2r2iSXnZDyRnVJcnOvA/bVqMJlzScFS0a7sPFVEtYcIk1kInVwdQ4ZR0yN+u8MzVRTVqdjJb8pgNs5oALudupJdt1H8J+venlqU+w0vyClYU+9GWx6ZIydwRfDEt0JqI16/meWQJaUO1ZJ4wK5/mDffj91b02IKrKnxfV2MscSNe+iwhvBxOIP5jUprjYec97zCBD1ZP0Zef5XbzJ7Vclvyss2AUAqU+XgQGYxx809r5Yz5FF6iNPFB50ypC0GdyHK2CDkEfEpz8nVjF8+KbHrHAHsHYnMZRZbqGLYhSNEVYHqPGYCG2eDl3cp4N7sX+yh/zgf76A/AevUA1EHtloQ+ily07uKUEhH46sgQMxMB1uwdK6AATBwCE3hDcTendQgxhzOnMA9PhLxjndB0VdETwBwKh5WLFYsQqjKXMbQsx1hDuvuubg4D+PeGOuBByLCgsl7vhSqT3B51rnNre3Zpu5LUt9c5AWQ7HPjj7OIL+KwQbz/AUUdl13YgppN/ESvivwmv10foy9+usTceKbJqUpsfZUUYSCwzrxa5csiTxwWbZ10y+KHqA=
    - GIT_NAME: Travis CI
    - GIT_EMAIL: dead-hosts@funilrys.com
    - TRAVIS_REPO_SLUG: Ultimate-Hosts-Blacklist/Top-Attacking-IP-Addresses-Against-Wordpress-Sites
    - GIT_BRANCH: master

dist: xenial
sudo: required
language: python

python:
  - "3.7"

matrix:
  fast_finish: true

cache:
  - pip

addons:
  apt:
    packages:
      - dos2unix

install:
  - pip3 install --upgrade pip
  - pip3 install requests

script:
  - python3 ./update.py

notifications:
  on_success:   change
  on_failure:   always
