env:
  global:
    - secure: fy40werG+DIkQ0Tpkp9tJPaqf81fNfdlPf0K4bveyePWdMOLAObR43A+mdUZtww3EGOderdfORp8sySFsRNP1tz15GlyxdLYFwkvIALYOM+krsKVzYZDqO52PGLFTil+6zd77jRTUWE+3AtMpo5J7c/aYj5bMglz0/K4JI6SFYqAdFgm1TTMr2fTY0eo1+RgksYFx9IwkeWjvqCoObe8u9x/K2qkl4c53BpSlvx5YnTxOsRXNB1jGPbwWCPF0onqDYslTcTgW2vsx7pOBMh6cp96O+66eqMzI0zd75NUgfImCTWivj3LZVNVj4yLOVlhHGBhVzhlwf00zvZVrfJa1NI9FzRY9oSXWl1qC7qt420J9IdGrHX/vkNPlR/2Z0VJ/k+AiWDP7H++3wnpLWUHXVJJ+J6YSYvTq1UulnhgrNHTMjUgZC+QAtVg5/JaghJzg6fxAgOSwDvJQ8XHubwesYemmLbsLcjG4JVA/Uzn+V9w4FWN3xOpDbLQwEl0Uz5MG9xexvsBOm1LAf66KwZVPxcGUFOqC+U9nfRFr6ZuUrir25vOCLd1tDTw+805a5kng1Oj3MjDP4nb1UcZA3mrgLrAKuTu1MIYJJeb8C51cr1jL6yssZazsj6OEcW6/rkZ/IfRqomyX1hx/kzhctLJ1y1n1eaCpcgN7+V4QnwkIe0=
    - GIT_NAME: Travis CI
    - GIT_EMAIL: dead-hosts@funilrys.com
    - TRAVIS_REPO_SLUG: Ultimate-Hosts-Blacklist/Top-Attacking-IP-Addresses-Against-Wordpress-Sites
    - GIT_BRANCH: master

dist: xenial
sudo: required
language: python

python:
  - "3.7"

matrix:
  fast_finish: true

cache:
  - pip

addons:
  apt:
    packages:
      - dos2unix

install:
  - pip3 install --upgrade pip
  - pip3 install requests

script:
  - python3 ./update.py

notifications:
  on_success:   change
  on_failure:   always
